#!/usr/bin/env python3
# Copyright 2006-2026 The QElectroTech Team
# This file is part of QElectroTech.
#
# QElectroTech is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# QElectroTech is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with QElectroTech.  If not, see <http://www.gnu.org/licenses/>.
"""Build QET's icon theme "qet" from the PNG and SVG sources in ico/.

Run from the repository root:

    python3 misc/make_icon_themes.py

It writes:

    ico/themes/qet/index.theme    the theme description
    ico/icon-themes.qrc           resource file listing the theme

The theme does not copy any file. The .qrc aliases the existing
ico/<size>/<name>.png files into the theme layout Qt's icon loader
expects (themes/qet/<size>/<name>.png), so QIcon::fromTheme("name")
finds them. Idempotent: running it twice changes nothing.
"""

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ICO = ROOT / "ico"
THEMES = ICO / "themes"
QRC = ICO / "icon-themes.qrc"

# Fixed-size folders that hold toolbar, menu and dialog icons. The 24x16
# flags, the 22x22/color swatches and the application icons are not theme
# icons and stay on their resource paths.
SIZES = ["16x16", "22x22", "32x32", "48x48", "128x128"]

# Table entries in sources/qeticons.cpp that pair a 16 pixel file with a
# 22 pixel file of another name. The theme needs one name per icon, so
# the 22 pixel file is exposed under the 16 pixel name as well.
ALIASES = {
    "22x22/conductor2.png": "conductor-reset",
    "22x22/diagram_add.png": "folio-new",
    "22x22/diagram_del.png": "folio-delete",
    "22x22/dialog-information.png": "folio-properties",
}

# SVG icons referenced from sources/qeticons.cpp.
SVGS = [
    "breeze-icons/scalable/apps/hidef/edit-opacity.svg",
    "breeze-icons/scalable/apps/hidef/image-flip-horizontal-symbolic.svg",
    "breeze-icons/scalable/apps/hidef/image-flip-vertical-symbolic.svg",
    "breeze-icons/scalable/apps/hidef/draw-bezier-curves.svg",
    "breeze-icons/scalable/apps/hidef/transform-crop.svg",
    "generated/ellipse-to-bezier.svg",
    "generated/rect-to-bezier.svg",
    "generated/rect-to-polyline.svg",
]


def write_if_changed(path, data):
    """Write text only when the content differs, so git stays quiet."""
    if path.exists() and path.read_text(encoding="utf-8") == data:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data, encoding="utf-8")
    return True


def index_theme(name, comment, dirs, inherits=None):
    lines = ["[Icon Theme]", f"Name={name}", f"Comment={comment}"]
    if inherits:
        lines.append(f"Inherits={inherits}")
    lines.append("Directories=" + ",".join(dirs))
    lines.append("")
    for d in dirs:
        lines.append(f"[{d}]")
        if d == "scalable":
            lines += ["Size=22", "Type=Scalable", "MinSize=8", "MaxSize=256"]
        else:
            lines += [f"Size={d.split('x')[0]}", "Type=Fixed"]
        lines.append("")
    return "\n".join(lines)


def main():
    entries = []   # (alias, source) pairs, paths relative to ico/
    changed = 0

    for size in SIZES:
        for png in sorted((ICO / size).glob("*.png")):
            rel = f"{size}/{png.name}"
            names = [png.stem]
            if rel in ALIASES:
                names.append(ALIASES[rel])
            for name in names:
                entries.append((f"themes/qet/{size}/{name}.png", rel))

    for rel in SVGS:
        name = re.sub(r"-symbolic(?=\.svg$)", "", Path(rel).name)
        entries.append((f"themes/qet/scalable/{name}", rel))

    dirs = SIZES + ["scalable"]
    changed += write_if_changed(THEMES / "qet" / "index.theme",
                                index_theme("qet", "QElectroTech icons", dirs))

    qrc = ["<!DOCTYPE RCC>", "<!-- Generated by misc/make_icon_themes.py. Do not edit. -->",
           '<RCC version="1.0">', '    <qresource prefix="/ico">',
           "        <file>themes/qet/index.theme</file>"]
    for alias, source in entries:
        qrc.append(f'        <file alias="{alias}">{source}</file>')
    qrc += ["    </qresource>", "</RCC>", ""]
    changed += write_if_changed(QRC, "\n".join(qrc))

    print(f"{len(entries)} theme entries; {changed} files written")


if __name__ == "__main__":
    os.chdir(ROOT)
    main()
