/*
	Copyright 2006-2026 The QElectroTech Team
	This file is part of QElectroTech.
	
	QElectroTech is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	QElectroTech is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with QElectroTech.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "qeticons.h"
#include <QApplication>

// on redeclare ici les icones
namespace QET {
	namespace Icons {
		QIcon Add;
		QIcon AddFolio;
		QIcon Allowed;
		QIcon ApplicationExit;
		QIcon ArrowLeft;
		QIcon ArrowLeftDouble;
		QIcon ArrowRight;
		QIcon ArrowRightDouble;
		QIcon Autoconnect;
		QIcon BringForward;
		QIcon Cancel;
		QIcon Company;
		QIcon Conductor;
		QIcon ConductorEdit;
		QIcon ConductorSettings;
		QIcon Configure;
		QIcon ConfigureShortcuts;
		QIcon ConfigureToolbars;
		QIcon IC_CopyFile;
		QIcon DefaultConductor;
		QIcon DiagramAdd;
		QIcon Diagram;
		QIcon DiagramBg;
		QIcon DiagramDelete;
		QIcon DialogCancel;
		QIcon DialogInformation;
		QIcon DialogOk;
		QIcon DocumentClose;
		QIcon DocumentExport;
		QIcon DocumentSpreadsheet;
		QIcon DocumentImport;
		QIcon DocumentNew;
		QIcon DocumentOpen;
		QIcon DocumentOpenRecent;
		QIcon DocumentPrint;
		QIcon DocumentPrintFrame;
		QIcon DocumentSave;
		QIcon DocumentSaveAll;
		QIcon DocumentSaveAs;
		QIcon East;
		QIcon EditClear;
		QIcon EditClearLocationBar;
		QIcon EditCopy;
		QIcon EditCut;
		QIcon EditDelete;
		QIcon EditOpacity;		
		QIcon EditPaste;
		QIcon EditRedo;
		QIcon EditRename;
		QIcon EditSelectAll;
		QIcon EditSelectInvert;
		QIcon EditSelectNone;
		QIcon EditTableCellMerge;
		QIcon EditTableCellSplit;
		QIcon EditTableDeleteColumn;
		QIcon EditTableDeleteRow;
		QIcon EditTableInsertColumnLeft;
		QIcon EditTableInsertColumnRight;
		QIcon EditTableInsertRowAbove;
		QIcon EditTableInsertRowUnder;
		QIcon EditText;
		QIcon EditUndo;
		QIcon Element;
		QIcon ElementDelete;
		QIcon ElementEdit;
		QIcon ElementNew;
		QIcon ElementSmall;
		QIcon EllipseToBezier;
		QIcon EndLineCircle;
		QIcon EndLineDiamond;
		QIcon EndLineNone;
		QIcon EndLineSimple;
		QIcon EndLineTriangle;
		QIcon EPS;
		QIcon Flip;
		QIcon Folder;
		QIcon FolderDelete;
		QIcon FolderEdit;
		QIcon FolderNew;
		QIcon FolderOnlyThis;
		QIcon FolderOpen;
		QIcon FolderProperties;
		QIcon FolderShowAll;
		QIcon Forbidden;
		QIcon FullScreenEnter;
		QIcon FullScreenExit;
		QIcon GoBottom;
		QIcon GoDown;
		QIcon GoDownDouble;
		QIcon GoTop;
		QIcon GoUp;
		QIcon GoUpDouble;
		QIcon Ground;
		QIcon Grid;
		QIcon Hide;
		QIcon Home;
		QIcon HotSpot;
		QIcon ImageFlipHorizontal;
		QIcon ImageFlipVertical;
		QIcon InsertImage;
		QIcon Lower;
		QIcon IC_MoveFile;
		QIcon Mirror;
		QIcon Names;
		QIcon Neutral;
		QIcon NewDiagram;
		QIcon North;
		QIcon ObjectLocked;
		QIcon ObjectRotateRight;
		QIcon ObjectUnlocked;
		QIcon Orientations;
		QIcon PartArc;
		QIcon PartBezier;
		QIcon PartCircle;
		QIcon PartEllipse;
		QIcon PartLine;
		QIcon PartPolygon;
		QIcon PartRectangle;
		QIcon PartSelect;
		QIcon PartText;
		QIcon PartTextField;
		QIcon PDF;
		QIcon Phase;
		QIcon PrintAllPages;
		QIcon Printer;
		QIcon PrintLandscape;
		QIcon PrintPortrait;
		QIcon PrintTwoPages;
		QIcon Project;
		QIcon ProjectClose;
		QIcon ProjectNew;
		QIcon Projects;
		QIcon ProjectFile;
		QIcon ProjectFileGP;
		QIcon ProjectProperties;
		QIcon QETIcon;
		QIcon QETLogo;
		QIcon QETOxygenLogo;
		QIcon QtLogo;
		QIcon Raise;
		QIcon RectToBezier;
		QIcon RectToPolyline;
		QIcon Remove;
		QIcon Restore;
		QIcon RunDxf;
		QIcon SendBackward;
		QIcon Settings;
		QIcon SinglePage;
		QIcon South;
		QIcon Start;
		QIcon TableOfContent;
		QIcon Terminal;
		QIcon TitleBlock;
		QIcon TitleBlockBottom;
		QIcon TitleBlockRight;
		QIcon TransformCrop;
		QIcon TransformRotate;
		QIcon UserInformations;
		QIcon ViewFitWidth;
		QIcon ViewFitWindow;
		QIcon ViewMove;
		QIcon ViewRefresh;
		QIcon West;
		QIcon WindowNew;
		QIcon XmlTextFile;
		QIcon ZoomDraw;
		QIcon ZoomFitBest;
		QIcon ZoomIn;
		QIcon ZoomOriginal;
		QIcon ZoomOut;
		QIcon adding_image;
		QIcon adding_pdf;
		QIcon resize_image;
		QIcon sa;
		QIcon br;
		QIcon catalonia;
		QIcon cs;
		QIcon de;
		QIcon da;
		QIcon gr;
		QIcon en;
		QIcon es;
		QIcon fr;
		QIcon hr;
		QIcon hu;
		QIcon it;
		QIcon jp;
		QIcon ko;
		QIcon pl;
		QIcon pt;
		QIcon ro;
		QIcon ru;
		QIcon sl;
		QIcon nl;
		QIcon no;
		QIcon nl_BE;
		QIcon tr;
		QIcon uk;
		QIcon mn;
		QIcon zh;
		QIcon se;
		QIcon translation;
		QIcon listDrawings;
		QIcon AutoNum;
		QIcon TerminalStrip;
		QIcon QETManual;
		QIcon QETDonate;
		QIcon QETDownload;
		QIcon QETVideo;
		QIcon super;
		QIcon sub;
		QIcon textGroup;
		QIcon ElementMaster;
		QIcon ElementSlave;
		QIcon FolioXrefComing;
		QIcon ElementTerminal;
		QIcon ColorBrown;
		QIcon ColorGray;
		QIcon ColorOrange;
		QIcon ColorPurple;
		QIcon ColorHTMLPinkPink;
		QIcon ColorHTMLPinkLightPink;
		QIcon ColorHTMLPinkHotPink;
		QIcon ColorHTMLPinkDeepPink;
		QIcon ColorHTMLPinkPaleVioletRed;
		QIcon ColorHTMLPinkMediumVioletRed;
		QIcon ColorHTMLRedLightSalmon;
		QIcon ColorHTMLRedSalmon;
		QIcon ColorHTMLRedDarkSalmon;
		QIcon ColorHTMLRedLightCoral;
		QIcon ColorHTMLRedIndianRed;
		QIcon ColorHTMLRedCrimson;
		QIcon ColorHTMLRedFirebrick;
		QIcon ColorHTMLRedDarkRed;
		QIcon ColorHTMLRedRed;
		QIcon ColorHTMLOrangeOrangeRed;
		QIcon ColorHTMLOrangeTomato;
		QIcon ColorHTMLOrangeCoral;
		QIcon ColorHTMLOrangeDarkOrange;
		QIcon ColorHTMLOrangeOrange;
		QIcon ColorHTMLYellowYellow;
		QIcon ColorHTMLYellowLightYellow;
		QIcon ColorHTMLYellowLemonChiffon;
		QIcon ColorHTMLYellowLightGoldenrodYellow;
		QIcon ColorHTMLYellowPapayaWhip;
		QIcon ColorHTMLYellowMoccasin;
		QIcon ColorHTMLYellowPeachPuff;
		QIcon ColorHTMLYellowPaleGoldenrod;
		QIcon ColorHTMLYellowKhaki;
		QIcon ColorHTMLYellowDarkKhaki;
		QIcon ColorHTMLYellowGold;
		QIcon ColorHTMLBrownCornsilk;
		QIcon ColorHTMLBrownBlanchedAlmond;
		QIcon ColorHTMLBrownBisque;
		QIcon ColorHTMLBrownNavajoWhite;
		QIcon ColorHTMLBrownWheat;
		QIcon ColorHTMLBrownBurlywood;
		QIcon ColorHTMLBrownTan;
		QIcon ColorHTMLBrownRosyBrown;
		QIcon ColorHTMLBrownSandyBrown;
		QIcon ColorHTMLBrownGoldenrod;
		QIcon ColorHTMLBrownDarkGoldenrod;
		QIcon ColorHTMLBrownPeru;
		QIcon ColorHTMLBrownChocolate;
		QIcon ColorHTMLBrownSaddleBrown;
		QIcon ColorHTMLBrownSienna;
		QIcon ColorHTMLBrownBrown;
		QIcon ColorHTMLBrownMaroon;
		QIcon ColorHTMLGreenDarkOliveGreen;
		QIcon ColorHTMLGreenOlive;
		QIcon ColorHTMLGreenOliveDrab;
		QIcon ColorHTMLGreenYellowGreen;
		QIcon ColorHTMLGreenLimeGreen;
		QIcon ColorHTMLGreenLime;
		QIcon ColorHTMLGreenLawnGreen;
		QIcon ColorHTMLGreenChartreuse;
		QIcon ColorHTMLGreenGreenYellow;
		QIcon ColorHTMLGreenSpringGreen;
		QIcon ColorHTMLGreenMediumSpringGreen;
		QIcon ColorHTMLGreenLightGreen;
		QIcon ColorHTMLGreenPaleGreen;
		QIcon ColorHTMLGreenDarkSeaGreen;
		QIcon ColorHTMLGreenMediumAquamarine;
		QIcon ColorHTMLGreenMediumSeaGreen;
		QIcon ColorHTMLGreenSeaGreen;
		QIcon ColorHTMLGreenForestGreen;
		QIcon ColorHTMLGreenGreen;
		QIcon ColorHTMLGreenDarkGreen;
		QIcon ColorHTMLCyanAqua;
		QIcon ColorHTMLCyanCyan;
		QIcon ColorHTMLCyanLightCyan;
		QIcon ColorHTMLCyanPaleTurquoise;
		QIcon ColorHTMLCyanAquamarine;
		QIcon ColorHTMLCyanTurquoise;
		QIcon ColorHTMLCyanMediumTurquoise;
		QIcon ColorHTMLCyanDarkTurquoise;
		QIcon ColorHTMLCyanLightSeaGreen;
		QIcon ColorHTMLCyanCadetBlue;
		QIcon ColorHTMLCyanDarkCyan;
		QIcon ColorHTMLCyanTeal;
		QIcon ColorHTMLBlueLightSteelBlue;
		QIcon ColorHTMLBluePowderBlue;
		QIcon ColorHTMLBlueLightBlue;
		QIcon ColorHTMLBlueSkyBlue;
		QIcon ColorHTMLBlueLightSkyBlue;
		QIcon ColorHTMLBlueDeepSkyBlue;
		QIcon ColorHTMLBlueDodgerBlue;
		QIcon ColorHTMLBlueCornflowerBlue;
		QIcon ColorHTMLBlueSteelBlue;
		QIcon ColorHTMLBlueRoyalBlue;
		QIcon ColorHTMLBlueBlue;
		QIcon ColorHTMLBlueMediumBlue;
		QIcon ColorHTMLBlueDarkBlue;
		QIcon ColorHTMLBlueNavy;
		QIcon ColorHTMLBlueMidnightBlue;
		QIcon ColorHTMLPurpleLavender;
		QIcon ColorHTMLPurpleThistle;
		QIcon ColorHTMLPurplePlum;
		QIcon ColorHTMLPurpleViolet;
		QIcon ColorHTMLPurpleOrchid;
		QIcon ColorHTMLPurpleFuchsia;
		QIcon ColorHTMLPurpleMagenta;
		QIcon ColorHTMLPurpleMediumOrchid;
		QIcon ColorHTMLPurpleMediumPurple;
		QIcon ColorHTMLPurpleBlueViolet;
		QIcon ColorHTMLPurpleDarkViolet;
		QIcon ColorHTMLPurpleDarkOrchid;
		QIcon ColorHTMLPurpleDarkMagenta;
		QIcon ColorHTMLPurplePurple;
		QIcon ColorHTMLPurpleIndigo;
		QIcon ColorHTMLPurpleDarkSlateBlue;
		QIcon ColorHTMLPurpleSlateBlue;
		QIcon ColorHTMLPurpleMediumSlateBlue;
		QIcon ColorHTMLWhiteWhite;
		QIcon ColorHTMLWhiteSnow;
		QIcon ColorHTMLWhiteHoneydew;
		QIcon ColorHTMLWhiteMintCream;
		QIcon ColorHTMLWhiteAzure;
		QIcon ColorHTMLWhiteAliceBlue;
		QIcon ColorHTMLWhiteGhostWhite;
		QIcon ColorHTMLWhiteWhiteSmoke;
		QIcon ColorHTMLWhiteSeashell;
		QIcon ColorHTMLWhiteBeige;
		QIcon ColorHTMLWhiteOldLace;
		QIcon ColorHTMLWhiteFloralWhite;
		QIcon ColorHTMLWhiteIvory;
		QIcon ColorHTMLWhiteAntiqueWhite;
		QIcon ColorHTMLWhiteLinen;
		QIcon ColorHTMLWhiteLavenderBlush;
		QIcon ColorHTMLWhiteMistyRose;
		QIcon ColorHTMLGrayGainsboro;
		QIcon ColorHTMLGrayLightGray;
		QIcon ColorHTMLGraySilver;
		QIcon ColorHTMLGrayDarkGray;
		QIcon ColorHTMLGrayGray;
		QIcon ColorHTMLGrayDimGray;
		QIcon ColorHTMLGrayLightSlateGray;
		QIcon ColorHTMLGraySlateGray;
		QIcon ColorHTMLGrayDarkSlateGray;
		QIcon ColorHTMLGrayBlack;
	}
}

/**
	Initialise les icones de l'application QElectroTech
*/
void QET::Icons::initIcons()
{
	// we may need to mirror some icons for right-to-left languages
	bool rtl = QApplication::isRightToLeft();
	QTransform reverse = QTransform().scale(-1, 1);
	
	Add                 = QIcon::fromTheme("list-add");
	AddFolio            = QIcon::fromTheme("folio-new");
	Allowed             = QIcon::fromTheme("user-online");
	ApplicationExit     = QIcon::fromTheme("application-exit");
	ArrowLeft           = QIcon::fromTheme("arrow-left");
	ArrowLeftDouble     = QIcon::fromTheme("arrow-left-double");
	ArrowRight          = QIcon::fromTheme("arrow-right");
	ArrowRightDouble    = QIcon::fromTheme("arrow-right-double");
	Autoconnect         = QIcon::fromTheme("autoconnect");
	BringForward        = QIcon::fromTheme("bring_forward");
	Cancel              = QIcon::fromTheme("item-cancel");
	Company             = QIcon::fromTheme("go-company");
	Conductor           = QIcon::fromTheme("conductor");
	ConductorEdit       = QIcon::fromTheme("conductor-edit");
	ConductorSettings   = QIcon::fromTheme("conductor-reset");
	Configure           = QIcon::fromTheme("configure");
	ConfigureShortcuts  = QIcon::fromTheme("configure-shortcuts");
	ConfigureToolbars   = QIcon::fromTheme("configure-toolbars");
	IC_CopyFile         = QIcon::fromTheme("item-copy");
	DiagramAdd          = QIcon::fromTheme("folio-new");
	Diagram.addFile(":/ico/16x16/diagram.png");
	Diagram.addFile(":/ico/diagram.png");
	DiagramBg           = QIcon::fromTheme("diagram_bg");
	DiagramDelete       = QIcon::fromTheme("folio-delete");
	DialogCancel        = QIcon::fromTheme("dialog-cancel");
	DialogInformation   = QIcon::fromTheme("folio-properties");
	DialogOk            = QIcon::fromTheme("dialog-ok");
	DocumentClose       = QIcon::fromTheme("document-close");
	DocumentExport      = QIcon::fromTheme("document-export");
	DocumentSpreadsheet = QIcon::fromTheme("export-csv");
	DocumentExport      = QIcon::fromTheme("document-export");
	DocumentImport      = QIcon::fromTheme("document-import");
	DocumentNew         = QIcon::fromTheme("document-new");
	DocumentOpen        = QIcon::fromTheme("document-open");
	DocumentOpenRecent  = QIcon::fromTheme("document-open-recent");
	DocumentPrint       = QIcon::fromTheme("document-print");
	DocumentPrintFrame  = QIcon::fromTheme("document-print-frame");
	DocumentSave        = QIcon::fromTheme("document-save");
	DocumentSaveAll     = QIcon::fromTheme("document-save-all");
	DocumentSaveAs      = QIcon::fromTheme("document-save-as");
	East                = QIcon::fromTheme("east");
	EditClear           = QIcon::fromTheme("edit-clear");
	EditText            = QIcon::fromTheme("names");
	adding_image        = QIcon::fromTheme("insert-image");
	adding_pdf          = QIcon::fromTheme("pdf-import");
	
	if (rtl) {
		EditClearLocationBar.addPixmap(QIcon::fromTheme("edit-clear-locationbar-ltr").pixmap(16).transformed(reverse));
		EditClearLocationBar.addPixmap(QIcon::fromTheme("edit-clear-locationbar-ltr").pixmap(22).transformed(reverse));
	} else {
		EditClearLocationBar= QIcon::fromTheme("edit-clear-locationbar-ltr");
	}
	EditCopy            = QIcon::fromTheme("edit-copy");
	EditCut             = QIcon::fromTheme("edit-cut");
	EditDelete          = QIcon::fromTheme("edit-delete");
	EditOpacity         = QIcon::fromTheme("edit-opacity");
	EditPaste           = QIcon::fromTheme("edit-paste");
	if (rtl) {
		EditRedo.addPixmap(QIcon::fromTheme("edit-redo").pixmap(16).transformed(reverse));
		EditRedo.addPixmap(QIcon::fromTheme("edit-redo").pixmap(22).transformed(reverse));
	} else {
		EditRedo            = QIcon::fromTheme("edit-redo");
	}
	EditRename          = QIcon::fromTheme("edit-rename");
	EditSelectAll       = QIcon::fromTheme("edit-select-all");
	EditSelectInvert    = QIcon::fromTheme("edit-select-invert");
	EditSelectNone      = QIcon::fromTheme("edit-select-none");
	EditTableCellMerge  = QIcon::fromTheme("edit-table-cell-merge");
	EditTableCellSplit  = QIcon::fromTheme("edit-table-cell-split");
	EditTableDeleteColumn= QIcon::fromTheme("edit-table-delete-column");
	EditTableDeleteRow  = QIcon::fromTheme("edit-table-delete-row");
	EditTableInsertColumnLeft= QIcon::fromTheme("edit-table-insert-column-left");
	EditTableInsertColumnRight= QIcon::fromTheme("edit-table-insert-column-right");
	EditTableInsertRowAbove= QIcon::fromTheme("edit-table-insert-row-above");
	EditTableInsertRowUnder= QIcon::fromTheme("edit-table-insert-row-under");
	if (rtl) {
		EditUndo.addPixmap(QIcon::fromTheme("edit-undo").pixmap(16).transformed(reverse));
		EditUndo.addPixmap(QIcon::fromTheme("edit-undo").pixmap(22).transformed(reverse));
	} else {
		EditUndo            = QIcon::fromTheme("edit-undo");
	}
	Element.addFile(":/ico/breeze-icons/16x16/mimetypes/application-x-qet-element.png");
	Element.addFile(":/ico/breeze-icons/22x22/mimetypes/application-x-qet-element.png");
	Element.addFile(":/ico/breeze-icons/32x32/mimetypes/application-x-qet-element.png");
	ElementDelete       = QIcon::fromTheme("element-delete");
	ElementEdit         = QIcon::fromTheme("element-edit");
	ElementNew          = QIcon::fromTheme("element-new");
	ElementSmall        = QIcon::fromTheme("element");
	EllipseToBezier     = QIcon::fromTheme("ellipse-to-bezier");
	EndLineCircle       = QIcon::fromTheme("endline-circle");
	EndLineDiamond      = QIcon::fromTheme("endline-diamond");
	EndLineNone         = QIcon::fromTheme("endline-none");
	EndLineSimple       = QIcon::fromTheme("endline-simple");
	EndLineTriangle     = QIcon::fromTheme("endline-triangle");
	EPS                 = QIcon::fromTheme("image-x-eps");
	Flip                = QIcon::fromTheme("flip");
	Folder              = QIcon::fromTheme("folder");
	FolderDelete        = QIcon::fromTheme("folder-delete");
	FolderEdit          = QIcon::fromTheme("folder-edit");
	FolderNew           = QIcon::fromTheme("folder-new");
	FolderOnlyThis      = QIcon::fromTheme("folder-only-this");
	FolderOpen          = QIcon::fromTheme("folder-open");
	FolderProperties    = QIcon::fromTheme("folder-properties");
	FolderShowAll       = QIcon::fromTheme("folder-show-all");
	Forbidden           = QIcon::fromTheme("user-busy");
	FullScreenEnter     = QIcon::fromTheme("view-fullscreen");
	FullScreenExit      = QIcon::fromTheme("view-restore");
	GoBottom            = QIcon::fromTheme("go-bottom");
	GoDown              = QIcon::fromTheme("go-down");
	GoDownDouble        = QIcon::fromTheme("go-down-double");
	GoTop               = QIcon::fromTheme("go-top");
	GoUp                = QIcon::fromTheme("go-up");
	GoUpDouble          = QIcon::fromTheme("go-up-double");
	Ground              = QIcon::fromTheme("ground");
	Grid                = QIcon::fromTheme("grid");
	Hide                = QIcon::fromTheme("masquer");
	Home                = QIcon::fromTheme("go-home");
	HotSpot             = QIcon::fromTheme("hotspot");
	ImageFlipHorizontal = QIcon::fromTheme("image-flip-horizontal");
	ImageFlipVertical   = QIcon::fromTheme("image-flip-vertical");
	InsertImage         = QIcon::fromTheme("insert-image");
	Lower               = QIcon::fromTheme("lower");
	IC_MoveFile         = QIcon::fromTheme("item-move");
	Mirror              = QIcon::fromTheme("mirror");
	Names               = QIcon::fromTheme("names");
	Neutral             = QIcon::fromTheme("neutral");
	NewDiagram          = QIcon::fromTheme("diagram");
	North               = QIcon::fromTheme("north");
	ObjectLocked        = QIcon::fromTheme("object-locked");
	ObjectRotateRight   = QIcon::fromTheme("object-rotate-right");
	ObjectUnlocked      = QIcon::fromTheme("object-unlocked");
	Orientations        = QIcon::fromTheme("orientations");
	PartArc             = QIcon::fromTheme("arc");
	PartBezier          = QIcon::fromTheme("draw-bezier-curves");
	PartCircle          = QIcon::fromTheme("circle");
	PartEllipse         = QIcon::fromTheme("ellipse");
	PartLine            = QIcon::fromTheme("line");
	PartPolygon         = QIcon::fromTheme("polygon");
	PartRectangle       = QIcon::fromTheme("rectangle");
	PartSelect          = QIcon::fromTheme("select");
	PartText            = QIcon::fromTheme("text");
	PartTextField       = QIcon::fromTheme("textfield");
	PDF                 = QIcon::fromTheme("application-pdf");
	Phase               = QIcon::fromTheme("phase");
	PrintAllPages       = QIcon::fromTheme("all_pages");
	Printer             = QIcon::fromTheme("printer");
	PrintLandscape      = QIcon::fromTheme("landscape");
	PrintPortrait       = QIcon::fromTheme("portrait");
	PrintTwoPages       = QIcon::fromTheme("two_pages");
	Projects            = QIcon::fromTheme("project");
	ProjectClose        = QIcon::fromTheme("project-close");
	ProjectNew          = QIcon::fromTheme("project-new");
	ProjectFile.addFile(":/ico/breeze-icons/16x16/mimetypes/application-x-qet-project.png");
	ProjectFile.addFile(":/ico/breeze-icons/22x22/mimetypes/application-x-qet-project.png");
	ProjectFile.addFile(":/ico/breeze-icons/32x32/mimetypes/application-x-qet-project.png");
	ProjectProperties   = QIcon::fromTheme("project-properties");
	QETDonate           = QIcon::fromTheme("help-donate");
	QETDownload         = QIcon::fromTheme("edit-download");
	QETIcon.addFile(":/ico/256x256/qelectrotech.png");
	// The elements panel shows the project root with this icon in a 50 px
	// slot meant for element previews. The theme name "project" also
	// carries the 128 px file used by the configuration dialog, and on a
	// 2x display Qt's theme loader would pick it and fill the slot. Load
	// the two small files directly so the item stays at 16/22 px.
	ProjectFileGP.addFile(":/ico/themes/qet/16x16/project.png");
	ProjectFileGP.addFile(":/ico/themes/qet/22x22/project.png");
	QETLogo             = QIcon::fromTheme("qet");
	QETManual           = QIcon::fromTheme("help-contents");
	QETLogo.addFile(":/ico/256x256/qet.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/128x128/apps/qelectrotech.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/16x16/apps/qelectrotech.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/22x22/apps/qelectrotech.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/256x256/apps/qelectrotech.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/32x32/apps/qelectrotech.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/48x48/apps/qelectrotech.png");
	QETOxygenLogo.addFile(":/ico/breeze-icons/64x64/apps/qelectrotech.png");
	QETVideo            = QIcon::fromTheme("kdenlive-show-video");
	QtLogo              = QIcon::fromTheme("qt");
	Raise               = QIcon::fromTheme("raise");
	RectToBezier        = QIcon::fromTheme("rect-to-bezier");
	RectToPolyline      = QIcon::fromTheme("rect-to-polyline");
	Remove              = QIcon::fromTheme("list-remove");
	resize_image        = QIcon::fromTheme("transform-scale");
	Restore             = QIcon::fromTheme("restaurer");
	RunDxf              = QIcon::fromTheme("run-dxf");
	SendBackward        = QIcon::fromTheme("send_backward");
	Settings            = QIcon::fromTheme("settings");
	SinglePage          = QIcon::fromTheme("single_page");
	South               = QIcon::fromTheme("south");
	Start               = QIcon::fromTheme("start");
	TableOfContent      = QIcon::fromTheme("table-of-content");
	Terminal            = QIcon::fromTheme("terminal");
	TerminalStrip       = QIcon::fromTheme("terminalstrip");
	TitleBlock          = QIcon::fromTheme("label");
	TitleBlockBottom    = QIcon::fromTheme("titleblock-bottom");
	TitleBlockRight     = QIcon::fromTheme("titleblock-right");
	TransformCrop       = QIcon::fromTheme("transform-crop");
	TransformRotate     = QIcon::fromTheme("transform-rotate");
	UserInformations    = QIcon::fromTheme("preferences-desktop-user");
	ViewFitWidth        = QIcon::fromTheme("view_fit_width");
	ViewFitWindow       = QIcon::fromTheme("view-fit-window");
	ViewMove            = QIcon::fromTheme("move");
	if (rtl) {
		ViewRefresh.addPixmap(QIcon::fromTheme("view-refresh").pixmap(16).transformed(reverse));
		ViewRefresh.addPixmap(QIcon::fromTheme("view-refresh").pixmap(22).transformed(reverse));
	} else {
		ViewRefresh         = QIcon::fromTheme("view-refresh");
	}
	West                = QIcon::fromTheme("west");
	WindowNew           = QIcon::fromTheme("window-new");
	XmlTextFile         = QIcon::fromTheme("text-xml");
	ZoomDraw            = QIcon::fromTheme("zoom-draw");
	ZoomFitBest         = QIcon::fromTheme("zoom-fit-best");
	ZoomIn              = QIcon::fromTheme("zoom-in");
	ZoomOriginal        = QIcon::fromTheme("zoom-original");
	ZoomOut             = QIcon::fromTheme("zoom-out");
	sa.addFile(":/ico/24x16/sa.png");
	br.addFile(":/ico/24x16/br.png");
	catalonia.addFile(":/ico/24x16/catalonia.png");
	cs.addFile(":/ico/24x16/cs.png");
	da.addFile(":/ico/24x16/dk.png");
	de.addFile(":/ico/24x16/de.png");
	gr.addFile(":/ico/24x16/gr.png");
	en.addFile(":/ico/24x16/en.png");
	es.addFile(":/ico/24x16/es.png");
	fr.addFile(":/ico/24x16/fr.png");
	hr.addFile(":/ico/24x16/hr.png");
	hu.addFile(":/ico/24x16/hu.png");
	it.addFile(":/ico/24x16/it.png");
	jp.addFile(":/ico/24x16/jp.png");
	ko.addFile(":/ico/24x16/kr.png");
	pl.addFile(":/ico/24x16/pl.png");
	pt.addFile(":/ico/24x16/pt.png");
	ro.addFile(":/ico/24x16/ro.png");
	ru.addFile(":/ico/24x16/ru.png");
	sl.addFile(":/ico/24x16/sl.png");
	nl.addFile(":/ico/24x16/nl.png");
	no.addFile(":/ico/24x16/no.png");
	nl_BE.addFile(":/ico/24x16/nl_BE.png");
	tr.addFile(":/ico/24x16/tr.png");
	uk.addFile(":/ico/24x16/ua.png");
	mn.addFile(":/ico/24x16/mn.png");
	zh.addFile(":/ico/24x16/zh.png");
	se.addFile(":/ico/24x16/se.png");
	translation         = QIcon::fromTheme("applications-development-translation");
	listDrawings        = QIcon::fromTheme("view-pim-journal");
	AutoNum             = QIcon::fromTheme("plasmagik");
	sub                 = QIcon::fromTheme("format-text-subscript");
	super               = QIcon::fromTheme("format-text-superscript");
	textGroup           = QIcon::fromTheme("object-group");
	ElementMaster       = QIcon::fromTheme("element-master");
	ElementSlave        = QIcon::fromTheme("element-slave");
	FolioXrefComing     = QIcon::fromTheme("folio-ref-coming");
	ElementTerminal     = QIcon::fromTheme("terminal");
	ColorBrown.addFile(":/ico/22x22/color/color-brown.png");
	ColorGray.addFile(":/ico/22x22/color/color-gray.png");
	ColorOrange.addFile(":/ico/22x22/color/color-orange.png");
	ColorPurple.addFile(":/ico/22x22/color/color-purple.png");
	ColorHTMLPinkPink.addFile(":/ico/22x22/color/color-01-pink-01-pink.png");
	ColorHTMLPinkLightPink.addFile(":/ico/22x22/color/color-01-pink-02-lightpink.png");
	ColorHTMLPinkHotPink.addFile(":/ico/22x22/color/color-01-pink-03-hotpink.png");
	ColorHTMLPinkDeepPink.addFile(":/ico/22x22/color/color-01-pink-04-deeppink.png");
	ColorHTMLPinkPaleVioletRed.addFile(":/ico/22x22/color/color-01-pink-05-palevioletred.png");
	ColorHTMLPinkMediumVioletRed.addFile(":/ico/22x22/color/color-01-pink-06-mediumvioletred.png");
	ColorHTMLRedLightSalmon.addFile(":/ico/22x22/color/color-02-red-01-lightsalmon.png");
	ColorHTMLRedSalmon.addFile(":/ico/22x22/color/color-02-red-02-salmon.png");
	ColorHTMLRedDarkSalmon.addFile(":/ico/22x22/color/color-02-red-03-darksalmon.png");
	ColorHTMLRedLightCoral.addFile(":/ico/22x22/color/color-02-red-04-lightcoral.png");
	ColorHTMLRedIndianRed.addFile(":/ico/22x22/color/color-02-red-05-indianred.png");
	ColorHTMLRedCrimson.addFile(":/ico/22x22/color/color-02-red-06-crimson.png");
	ColorHTMLRedFirebrick.addFile(":/ico/22x22/color/color-02-red-07-firebrick.png");
	ColorHTMLRedDarkRed.addFile(":/ico/22x22/color/color-02-red-08-darkred.png");
	ColorHTMLRedRed.addFile(":/ico/22x22/color/color-02-red-09-red.png");
	ColorHTMLOrangeOrangeRed.addFile(":/ico/22x22/color/color-03-orange-01-orangered.png");
	ColorHTMLOrangeTomato.addFile(":/ico/22x22/color/color-03-orange-02-tomato.png");
	ColorHTMLOrangeCoral.addFile(":/ico/22x22/color/color-03-orange-03-coral.png");
	ColorHTMLOrangeDarkOrange.addFile(":/ico/22x22/color/color-03-orange-04-darkorange.png");
	ColorHTMLOrangeOrange.addFile(":/ico/22x22/color/color-03-orange-05-orange.png");
	ColorHTMLYellowYellow.addFile(":/ico/22x22/color/color-04-yellow-01-yellow.png");
	ColorHTMLYellowLightYellow.addFile(":/ico/22x22/color/color-04-yellow-02-lightyellow.png");
	ColorHTMLYellowLemonChiffon.addFile(":/ico/22x22/color/color-04-yellow-03-lemonchiffon.png");
	ColorHTMLYellowLightGoldenrodYellow.addFile(":/ico/22x22/color/color-04-yellow-04-lightgoldenrodyellow.png");
	ColorHTMLYellowPapayaWhip.addFile(":/ico/22x22/color/color-04-yellow-05-papayawhip.png");
	ColorHTMLYellowMoccasin.addFile(":/ico/22x22/color/color-04-yellow-06-moccasin.png");
	ColorHTMLYellowPeachPuff.addFile(":/ico/22x22/color/color-04-yellow-07-peachpuff.png");
	ColorHTMLYellowPaleGoldenrod.addFile(":/ico/22x22/color/color-04-yellow-08-palegoldenrod.png");
	ColorHTMLYellowKhaki.addFile(":/ico/22x22/color/color-04-yellow-09-khaki.png");
	ColorHTMLYellowDarkKhaki.addFile(":/ico/22x22/color/color-04-yellow-10-darkkhaki.png");
	ColorHTMLYellowGold.addFile(":/ico/22x22/color/color-04-yellow-11-gold.png");
	ColorHTMLBrownCornsilk.addFile(":/ico/22x22/color/color-05-brown-01-cornsilk.png");
	ColorHTMLBrownBlanchedAlmond.addFile(":/ico/22x22/color/color-05-brown-02-blanchedalmond.png");
	ColorHTMLBrownBisque.addFile(":/ico/22x22/color/color-05-brown-03-bisque.png");
	ColorHTMLBrownNavajoWhite.addFile(":/ico/22x22/color/color-05-brown-04-navajowhite.png");
	ColorHTMLBrownWheat.addFile(":/ico/22x22/color/color-05-brown-05-wheat.png");
	ColorHTMLBrownBurlywood.addFile(":/ico/22x22/color/color-05-brown-06-burlywood.png");
	ColorHTMLBrownTan.addFile(":/ico/22x22/color/color-05-brown-07-tan.png");
	ColorHTMLBrownRosyBrown.addFile(":/ico/22x22/color/color-05-brown-08-rosybrown.png");
	ColorHTMLBrownSandyBrown.addFile(":/ico/22x22/color/color-05-brown-09-sandybrown.png");
	ColorHTMLBrownGoldenrod.addFile(":/ico/22x22/color/color-05-brown-10-goldenrod.png");
	ColorHTMLBrownDarkGoldenrod.addFile(":/ico/22x22/color/color-05-brown-11-darkgoldenrod.png");
	ColorHTMLBrownPeru.addFile(":/ico/22x22/color/color-05-brown-12-peru.png");
	ColorHTMLBrownChocolate.addFile(":/ico/22x22/color/color-05-brown-13-chocolate.png");
	ColorHTMLBrownSaddleBrown.addFile(":/ico/22x22/color/color-05-brown-14-saddlebrown.png");
	ColorHTMLBrownSienna.addFile(":/ico/22x22/color/color-05-brown-15-sienna.png");
	ColorHTMLBrownBrown.addFile(":/ico/22x22/color/color-05-brown-16-brown.png");
	ColorHTMLBrownMaroon.addFile(":/ico/22x22/color/color-05-brown-17-maroon.png");
	ColorHTMLGreenDarkOliveGreen.addFile(":/ico/22x22/color/color-06-green-01-darkolivegreen.png");
	ColorHTMLGreenOlive.addFile(":/ico/22x22/color/color-06-green-02-olive.png");
	ColorHTMLGreenOliveDrab.addFile(":/ico/22x22/color/color-06-green-03-olivedrab.png");
	ColorHTMLGreenYellowGreen.addFile(":/ico/22x22/color/color-06-green-04-yellowgreen.png");
	ColorHTMLGreenLimeGreen.addFile(":/ico/22x22/color/color-06-green-05-limegreen.png");
	ColorHTMLGreenLime.addFile(":/ico/22x22/color/color-06-green-06-lime.png");
	ColorHTMLGreenLawnGreen.addFile(":/ico/22x22/color/color-06-green-07-lawngreen.png");
	ColorHTMLGreenChartreuse.addFile(":/ico/22x22/color/color-06-green-08-chartreuse.png");
	ColorHTMLGreenGreenYellow.addFile(":/ico/22x22/color/color-06-green-09-greenyellow.png");
	ColorHTMLGreenSpringGreen.addFile(":/ico/22x22/color/color-06-green-10-springgreen.png");
	ColorHTMLGreenMediumSpringGreen.addFile(":/ico/22x22/color/color-06-green-11-mediumspringgreen.png");
	ColorHTMLGreenLightGreen.addFile(":/ico/22x22/color/color-06-green-12-lightgreen.png");
	ColorHTMLGreenPaleGreen.addFile(":/ico/22x22/color/color-06-green-13-palegreen.png");
	ColorHTMLGreenDarkSeaGreen.addFile(":/ico/22x22/color/color-06-green-14-darkseagreen.png");
	ColorHTMLGreenMediumAquamarine.addFile(":/ico/22x22/color/color-06-green-15-mediumaquamarine.png");
	ColorHTMLGreenMediumSeaGreen.addFile(":/ico/22x22/color/color-06-green-16-mediumseagreen.png");
	ColorHTMLGreenSeaGreen.addFile(":/ico/22x22/color/color-06-green-17-seagreen.png");
	ColorHTMLGreenForestGreen.addFile(":/ico/22x22/color/color-06-green-18-forestgreen.png");
	ColorHTMLGreenGreen.addFile(":/ico/22x22/color/color-06-green-19-green.png");
	ColorHTMLGreenDarkGreen.addFile(":/ico/22x22/color/color-06-green-20-darkgreen.png");
	ColorHTMLCyanAqua.addFile(":/ico/22x22/color/color-07-cyan-01-aqua.png");
	ColorHTMLCyanCyan.addFile(":/ico/22x22/color/color-07-cyan-02-cyan.png");
	ColorHTMLCyanLightCyan.addFile(":/ico/22x22/color/color-07-cyan-03-lightcyan.png");
	ColorHTMLCyanPaleTurquoise.addFile(":/ico/22x22/color/color-07-cyan-04-paleturquoise.png");
	ColorHTMLCyanAquamarine.addFile(":/ico/22x22/color/color-07-cyan-05-aquamarine.png");
	ColorHTMLCyanTurquoise.addFile(":/ico/22x22/color/color-07-cyan-06-turquoise.png");
	ColorHTMLCyanMediumTurquoise.addFile(":/ico/22x22/color/color-07-cyan-07-mediumturquoise.png");
	ColorHTMLCyanDarkTurquoise.addFile(":/ico/22x22/color/color-07-cyan-08-darkturquoise.png");
	ColorHTMLCyanLightSeaGreen.addFile(":/ico/22x22/color/color-07-cyan-09-lightseagreen.png");
	ColorHTMLCyanCadetBlue.addFile(":/ico/22x22/color/color-07-cyan-10-cadetblue.png");
	ColorHTMLCyanDarkCyan.addFile(":/ico/22x22/color/color-07-cyan-11-darkcyan.png");
	ColorHTMLCyanTeal.addFile(":/ico/22x22/color/color-07-cyan-12-teal.png");
	ColorHTMLBlueLightSteelBlue.addFile(":/ico/22x22/color/color-08-blue-01-lightsteelblue.png");
	ColorHTMLBluePowderBlue.addFile(":/ico/22x22/color/color-08-blue-02-powderblue.png");
	ColorHTMLBlueLightBlue.addFile(":/ico/22x22/color/color-08-blue-03-lightblue.png");
	ColorHTMLBlueSkyBlue.addFile(":/ico/22x22/color/color-08-blue-04-skyblue.png");
	ColorHTMLBlueLightSkyBlue.addFile(":/ico/22x22/color/color-08-blue-05-lightskyblue.png");
	ColorHTMLBlueDeepSkyBlue.addFile(":/ico/22x22/color/color-08-blue-06-deepskyblue.png");
	ColorHTMLBlueDodgerBlue.addFile(":/ico/22x22/color/color-08-blue-07-dodgerblue.png");
	ColorHTMLBlueCornflowerBlue.addFile(":/ico/22x22/color/color-08-blue-08-cornflowerblue.png");
	ColorHTMLBlueSteelBlue.addFile(":/ico/22x22/color/color-08-blue-09-steelblue.png");
	ColorHTMLBlueRoyalBlue.addFile(":/ico/22x22/color/color-08-blue-10-royalblue.png");
	ColorHTMLBlueBlue.addFile(":/ico/22x22/color/color-08-blue-11-blue.png");
	ColorHTMLBlueMediumBlue.addFile(":/ico/22x22/color/color-08-blue-12-mediumblue.png");
	ColorHTMLBlueDarkBlue.addFile(":/ico/22x22/color/color-08-blue-13-darkblue.png");
	ColorHTMLBlueNavy.addFile(":/ico/22x22/color/color-08-blue-14-navy.png");
	ColorHTMLBlueMidnightBlue.addFile(":/ico/22x22/color/color-08-blue-15-midnightblue.png");
	ColorHTMLPurpleLavender.addFile(":/ico/22x22/color/color-09-purple-01-lavender.png");
	ColorHTMLPurpleThistle.addFile(":/ico/22x22/color/color-09-purple-02-thistle.png");
	ColorHTMLPurplePlum.addFile(":/ico/22x22/color/color-09-purple-03-plum.png");
	ColorHTMLPurpleViolet.addFile(":/ico/22x22/color/color-09-purple-04-violet.png");
	ColorHTMLPurpleOrchid.addFile(":/ico/22x22/color/color-09-purple-05-orchid.png");
	ColorHTMLPurpleFuchsia.addFile(":/ico/22x22/color/color-09-purple-06-fuchsia.png");
	ColorHTMLPurpleMagenta.addFile(":/ico/22x22/color/color-09-purple-07-magenta.png");
	ColorHTMLPurpleMediumOrchid.addFile(":/ico/22x22/color/color-09-purple-08-mediumorchid.png");
	ColorHTMLPurpleMediumPurple.addFile(":/ico/22x22/color/color-09-purple-09-mediumpurple.png");
	ColorHTMLPurpleBlueViolet.addFile(":/ico/22x22/color/color-09-purple-10-blueviolet.png");
	ColorHTMLPurpleDarkViolet.addFile(":/ico/22x22/color/color-09-purple-11-darkviolet.png");
	ColorHTMLPurpleDarkOrchid.addFile(":/ico/22x22/color/color-09-purple-12-darkorchid.png");
	ColorHTMLPurpleDarkMagenta.addFile(":/ico/22x22/color/color-09-purple-13-darkmagenta.png");
	ColorHTMLPurplePurple.addFile(":/ico/22x22/color/color-09-purple-14-purple.png");
	ColorHTMLPurpleIndigo.addFile(":/ico/22x22/color/color-09-purple-15-indigo.png");
	ColorHTMLPurpleDarkSlateBlue.addFile(":/ico/22x22/color/color-09-purple-16-darkslateblue.png");
	ColorHTMLPurpleSlateBlue.addFile(":/ico/22x22/color/color-09-purple-17-slateblue.png");
	ColorHTMLPurpleMediumSlateBlue.addFile(":/ico/22x22/color/color-09-purple-18-mediumslateblue.png");
	ColorHTMLWhiteWhite.addFile(":/ico/22x22/color/color-10-white-01-white.png");
	ColorHTMLWhiteSnow.addFile(":/ico/22x22/color/color-10-white-02-snow.png");
	ColorHTMLWhiteHoneydew.addFile(":/ico/22x22/color/color-10-white-03-honeydew.png");
	ColorHTMLWhiteMintCream.addFile(":/ico/22x22/color/color-10-white-04-mintcream.png");
	ColorHTMLWhiteAzure.addFile(":/ico/22x22/color/color-10-white-05-azure.png");
	ColorHTMLWhiteAliceBlue.addFile(":/ico/22x22/color/color-10-white-06-aliceblue.png");
	ColorHTMLWhiteGhostWhite.addFile(":/ico/22x22/color/color-10-white-07-ghostwhite.png");
	ColorHTMLWhiteWhiteSmoke.addFile(":/ico/22x22/color/color-10-white-08-whitesmoke.png");
	ColorHTMLWhiteSeashell.addFile(":/ico/22x22/color/color-10-white-09-seashell.png");
	ColorHTMLWhiteBeige.addFile(":/ico/22x22/color/color-10-white-10-beige.png");
	ColorHTMLWhiteOldLace.addFile(":/ico/22x22/color/color-10-white-11-oldlace.png");
	ColorHTMLWhiteFloralWhite.addFile(":/ico/22x22/color/color-10-white-12-floralwhite.png");
	ColorHTMLWhiteIvory.addFile(":/ico/22x22/color/color-10-white-13-ivory.png");
	ColorHTMLWhiteAntiqueWhite.addFile(":/ico/22x22/color/color-10-white-14-antiquewhite.png");
	ColorHTMLWhiteLinen.addFile(":/ico/22x22/color/color-10-white-15-linen.png");
	ColorHTMLWhiteLavenderBlush.addFile(":/ico/22x22/color/color-10-white-16-lavenderblush.png");
	ColorHTMLWhiteMistyRose.addFile(":/ico/22x22/color/color-10-white-17-mistyrose.png");
	ColorHTMLGrayGainsboro.addFile(":/ico/22x22/color/color-11-gray-01-gainsboro.png");
	ColorHTMLGrayLightGray.addFile(":/ico/22x22/color/color-11-gray-02-lightgray.png");
	ColorHTMLGraySilver.addFile(":/ico/22x22/color/color-11-gray-03-silver.png");
	ColorHTMLGrayDarkGray.addFile(":/ico/22x22/color/color-11-gray-04-darkgray.png");
	ColorHTMLGrayGray.addFile(":/ico/22x22/color/color-11-gray-05-gray.png");
	ColorHTMLGrayDimGray.addFile(":/ico/22x22/color/color-11-gray-06-dimgray.png");
	ColorHTMLGrayLightSlateGray.addFile(":/ico/22x22/color/color-11-gray-07-lightslategray.png");
	ColorHTMLGraySlateGray.addFile(":/ico/22x22/color/color-11-gray-08-slategray.png");
	ColorHTMLGrayDarkSlateGray.addFile(":/ico/22x22/color/color-11-gray-09-darkslategray.png");
	ColorHTMLGrayBlack.addFile(":/ico/22x22/color/color-11-gray-10-black.png");
}
