/*
	Copyright 2006-2026 The QElectroTech Team
	This file is part of QElectroTech.

	QElectroTech is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.

	QElectroTech is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with QElectroTech.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "qetsbom.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>

// Generated by cmake/generate_sbom.cmake at configure time from whatever
// find_package()/FetchContent resolution this build actually used.
#include "sbom_data.h"

QList<QetSbomComponent> QetSbom::components()
{
	QList<QetSbomComponent> list;

	const QJsonDocument doc = QJsonDocument::fromJson(QByteArray(qet_sbom_json));
	const QJsonArray components = doc.object().value("components").toArray();

	for (const QJsonValue &value : components)
	{
		const QJsonObject obj = value.toObject();
		list.append({
			obj.value("name").toString(),
			obj.value("version").toString(),
			obj.value("license").toString(),
			obj.value("homepage").toString(),
			obj.value("source").toString()
		});
	}

	return list;
}

QString QetSbom::rawJson()
{
	return QString::fromUtf8(qet_sbom_json);
}
