        LangString wrongArch         ${LANG_FRENCH}  "Ce programme est pour Windows 64 bits seulement."
        LangString installed         ${LANG_FRENCH}  "${SOFT_NAME} est déja installé. $\n$\nCliquer sur `OK` pour désinstaller l'ancienne version `Annuler` pour annuler cet upgrade."
        LangString Elements          ${LANG_FRENCH}  "Eléments"
        LangString Electric          ${LANG_FRENCH}  "Electrique"
        LangString Logic             ${LANG_FRENCH}  "Logique"
        LangString Hydraulic         ${LANG_FRENCH}  "Hydraulique"
        LangString Pneumatic         ${LANG_FRENCH}  "Pneumatique"
        LangString Energy            ${LANG_FRENCH}  "Energie"
        LangString water             ${LANG_FRENCH}  "Eaux"
        LangString Refrigeration     ${LANG_FRENCH}  "Climatisation"
        LangString Solar_thermal     ${LANG_FRENCH}  "Thermique & solaire"
        LangString Lang              ${LANG_FRENCH}  "Langues"
        LangString Fonts             ${LANG_FRENCH}  "Polices"
        LangString Titleblocks       ${LANG_FRENCH}  "Cartouches"
        LangString Examples          ${LANG_FRENCH}  "Exemples"
        LangString Check             ${LANG_FRENCH}  "Cocher pour lancer ${SOFT_NAME}"
        LangString var1              ${LANG_FRENCH}  "Eléments de la collection officielle"
        LangString var2              ${LANG_FRENCH}  "Fichiers de langues"
        LangString var3              ${LANG_FRENCH}  "Exemples de cartouches"
        LangString var4              ${LANG_FRENCH}  "Exemples de schémas"
        LangString var5              ${LANG_FRENCH}  "Polices"
        LangString Mcp               ${LANG_FRENCH}  "Assistant IA (MCP)"
        LangString var6              ${LANG_FRENCH}  "Permet à un assistant IA d'ouvrir, vérifier et modifier vos schémas. Nécessite Python : le vôtre, ou celui proposé ci-dessous"
        LangString McpPython         ${LANG_FRENCH}  "Python pour l'assistant IA"
        LangString var7              ${LANG_FRENCH}  "Python de python.org, utilisé uniquement par le composant Assistant IA. Inutile si Python est déjà installé (environ 12 Mo)"
        LangString uninstFailed      ${LANG_FRENCH}  "La désinstallation de la version précédente a échoué.$\nVeuillez désinstaller ${SOFT_NAME} manuellement avant de continuer."
