name: Create Doxygen documentation for each change

on:
  push:
    branches:
      - master
      #! only for test, remove before MR !
      - ci/cd

jobs:
  build_amd64:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt install doxygen -y
    - name: Generate Doxyfile output
      run: doxygen Doxyfile
    - uses: actions/upload-artifact@v4
      with:
       name: Artifact XML Doxyfile output
       path: doc/xml