name: Auto-build doxygen docs
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      artifact-name:
        value: doxygen-html

jobs:
  doxygen:
    permissions:
       contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        show-progress: ''
    - name: Setup and run doxygen
      run: sudo apt update && sudo apt install doxygen graphviz qhelpgenerator-qt5 -y
    - name: Set up Git LFS
      run: |
          git lfs install
          git lfs track "*.qch"
    - name: Run doxygen
      run: doxygen Doxyfile
    - name: Create Pull Request
      if: startsWith(github.ref, 'refs/tags/')
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.MR_TOKEN }}
        commit-message: update QCH file
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        title: Update QCH Help file
        body: |
         - Updating QT Help file following commit ${{ github.sha }}.
         - Auto-generated by [create-pull-request][1]

         [1]: https://github.com/peter-evans/create-pull-request
        branch: update-qch
        labels: |
          qch
          cicd
        delete-branch: true
        add-paths: doc/*.qch

    - name: Upload HTML docs artifact
      uses: actions/upload-artifact@v7
      with:
        name: doxygen-html
        path: doc/html/
        retention-days: 40
