name: Build Flatpak package

on:
  push:
    branches:
      - master

jobs:
  flatpak:
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-5.15-24.08      
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        show-progress: ''
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
          bundle: qelectrotech.flatpak
          manifest-path: build-aux/flatpak/org.qelectrotech.QElectroTech.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          verbose: true  
    